### ISSUE TITLE
Cloud: Edit Labour issues

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#8]
The popup header should say Edit Labour, button should not say: "Add", should say "Update".

Reason is not coming populated.

![image](https://cloud.githubusercontent.com/assets/5666297/11850018/f0b8e2fe-a3f8-11e5-8a18-cf3db0397202.png)

**Comment by d3sqa** [comment]
Edit Labour feature has been incorporated at development environment

**Comment by giovanicani** [comment]
FULL OF BUGS! Notes not available, after inserting labour line, and editing, labour line gets duplicated, triplicated

![image](https://cloud.githubusercontent.com/assets/5666297/12012523/cfded6ac-acc6-11e5-9f48-e68f37f755c1.png)

**Comment by d3sqa** [comment]
When QUOTE is created and labour is added then that time labour name will be same. However, after pressing save button, if same labour exists two or three times then numbering will appear with labour name for differentiation. Labour lines did not gets duplicated, triplicated. 

![screenshot_573](https://cloud.githubusercontent.com/assets/13255706/12016922/73ebadc8-ad72-11e5-80ee-32558a2f1ddc.png)

Done. Fixed at Development Environment. It will be available in the next release at UAT

**Comment by giovanicani** [comment]
Still not working...

1. Reason should be mandatory
2. When creating Quote, insert labour line, press add... then double click again on labour line change and press add again, new line is created. Need to update not add new.

**Comment by d3sqa** [comment]
work in progress

**Comment by giovanicani** [comment]
please provide update.

**Comment by d3sqa** [comment]
Update feature is implemented i.e. the labour line which is double clicked will be updated instead of adding a new labour line.

Following features are implemented while editing labour at both Edit Quote and Add Quote forms:

1. Updating labour description
2. Updating Position
3. Updating Reason [Made it mandatory as well]
4. Updating Quote Hours
5. Updating Notes

Ready to test in development environment

**Comment by giovanicani** [comment]
As seen on the meeting, notes labour notes are not working. 
1. On first labour line, sometimes the notes does not show when editing.
2. After adding a second labour line, seems that the first labour notes was updated with the second labour note.

**Comment by d3sqa** [comment]
Following points are done and ready to test in development environment:


1. On first labour line, sometimes the notes does not show when editing.
2. After adding a second labour line, seems that the first labour notes was updated with the second labour note.

**Comment by giovanicani** [comment]
Giovani to test.

**Comment by giovanicani** [comment]
Still found bugs on insert form:

1. When creating new Quote, adding labour, I see the image icon popping up. Should not have an icon, as there are no images at this point. This seems to happen only on the insert form.

2. On insert form, adding a part with no id, then add part with id, then go and edit part without ID, it gets replaced with part with ID.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
While adding labour, when there is no image, no icon will be displayed against the labour. Done and ready to test
Work in progress on point # 02 and point # 03

**Comment by d3sqa** [comment]
Inline editing feature has been implemented at Add Quote form for Hour Rate (Labour) and Charge Rate (Part). Work in progress on Point # 02

**Comment by d3sqa** [comment]
Point # 2 has been done:

- Add a part without part # 
- Add a part with part # 
- Edit the part with out part # 
- It will not be replaced with the part having a part # 

Ready to test in development environment

**Comment by giovanicani** [comment]
will test and provide update


On Mon, Jan 11, 2016 at 2:51 AM, d3sqa <notifications@github.com> wrote:

> Point # 2 has been done:
>
>    - Add a part without part #
>    - Add a part with part #
>    - Edit the part with out part #
>    - It will not be replaced with the part having a part #
>
> Ready to test in development environment
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GCSO2/D3S-QUOTE/issues/8#issuecomment-170457063>.
>



-- 
Giovani Cani
Project Manager (PMP, CSM & OCP)
Software Delivery Services
Phone: (416) 848-7371

**Comment by giovanicani** [comment]
almost there... works nicely. Just please add 2 decimals on the update form. also make sure all fonts are the same size. Do this for Part and Labour $$$

![image](https://cloud.githubusercontent.com/assets/5666297/12238930/48733f16-b854-11e5-899d-7d04dc4607e3.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Up to two decimal points are now allowed at Hourly Rate, Quote Hrs, Charge and QTY. Ready to test in development environment

**Comment by giovanicani** [comment]
This is still not working, see screen shot below. It should show .00 in this case.

Please fix! **Make sure this is done for parts and labour**

![image](https://cloud.githubusercontent.com/assets/5666297/12263915/d2fe831e-b900-11e5-8b2f-670127f755d4.png)

**Comment by d3sqa** [comment]
Done at development for both Create and Edit Quote. Please see screenshot below:

![dsdsdsdsd](https://cloud.githubusercontent.com/assets/13255706/12323572/4c5d5666-bade-11e5-8709-0a3fd464177f.png)

Alternatively, when 12.1 is entered, it will be converted to 12.10

**Comment by giovanicani** [comment]
Need to add the 2 decimals on the labour ADD function on the create quote.

All else is working, please do this as soon as possible so that the ticket can be closed. Thanks!

**Comment by d3sqa** [comment]
When the labour is added, the labour hourly rate will have .00 by default. Please check now

**Comment by giovanicani** [comment]
works. thanks.
